/*

 Copyright 2017 The Lighthouse Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
class CategoryRenderer{constructor(a,b){this.dom=a;this.detailsRenderer=b;this.templateContext=this.dom.document();this.detailsRenderer.setTemplateContext(this.templateContext)}get _clumpTitles(){return{warning:Util.i18n.strings.warningAuditsGroupTitle,manual:Util.i18n.strings.manualAuditsGroupTitle,passed:Util.i18n.strings.passedAuditsGroupTitle,notApplicable:Util.i18n.strings.notApplicableAuditsGroupTitle}}renderAudit(a){const b=this.dom.cloneTemplate("#tmpl-lh-audit",this.templateContext);return this.populateAuditValues(a,
b)}populateAuditValues(a,b){var c=Util.i18n.strings;const d=this.dom.find(".lh-audit",b);d.id=a.result.id;b=a.result.scoreDisplayMode;a.result.displayValue&&(this.dom.find(".lh-audit__display-text",d).textContent=a.result.displayValue);const e=this.dom.find(".lh-audit__title",d);e.appendChild(this.dom.convertMarkdownCodeSnippets(a.result.title));var f=this.dom.find(".lh-audit__description",d);f.appendChild(this.dom.convertMarkdownLinkSnippets(a.result.description));for(var g of a.relevantMetrics||
[]){const h=this.dom.createChildOf(f,"span","lh-audit__adorn",{title:`Relevant to ${g.result.title}`});h.textContent=g.acronym||g.id}a.stackPacks&&a.stackPacks.forEach(h=>{const k=this.dom.createElement("div");k.classList.add("lh-audit__stackpack");const p=this.dom.createElement("img");p.classList.add("lh-audit__stackpack__img");p.src=h.iconDataURL;p.alt=h.title;k.appendChild(p);k.appendChild(this.dom.convertMarkdownLinkSnippets(h.description));this.dom.find(".lh-audit__stackpacks",d).appendChild(k)});
g=this.dom.find("details",d);a.result.details&&(f=this.detailsRenderer.render(a.result.details))&&(f.classList.add("lh-details"),g.appendChild(f));this.dom.find(".lh-chevron-container",d).appendChild(this._createChevron());this._setRatingClass(d,a.result.score,b);"error"===a.result.scoreDisplayMode?(d.classList.add("lh-audit--error"),b=this.dom.find(".lh-audit__display-text",d),b.textContent=c.errorLabel,b.classList.add("tooltip-boundary"),b=this.dom.createChildOf(b,"div","tooltip tooltip--error"),
b.textContent=a.result.errorMessage||c.errorMissingAuditInfo):a.result.explanation&&(b=this.dom.createChildOf(e,"div","lh-audit-explanation"),b.textContent=a.result.explanation);a=a.result.warnings;if(!a||0===a.length)return d;g=this.dom.find("summary",g);g=this.dom.createChildOf(g,"div","lh-warnings");this.dom.createChildOf(g,"span").textContent=c.warningHeader;if(1===a.length)g.appendChild(this.dom.document().createTextNode(a.join("")));else{c=this.dom.createChildOf(g,"ul");for(const h of a)a=this.dom.createChildOf(c,
"li"),a.textContent=h}return d}_createChevron(){var a=this.dom.cloneTemplate("#tmpl-lh-chevron",this.templateContext);return a=this.dom.find("svg.lh-chevron",a)}_setRatingClass(a,b,c){b=Util.calculateRating(b,c);a.classList.add(`lh-audit--${c.toLowerCase()}`);"informative"!==c&&a.classList.add(`lh-audit--${b}`);return a}renderCategoryHeader(a,b){const c=this.dom.cloneTemplate("#tmpl-lh-category-header",this.templateContext),d=this.dom.find(".lh-score__gauge",c);b=this.renderScoreGauge(a,b);d.appendChild(b);
a.description&&(a=this.dom.convertMarkdownLinkSnippets(a.description),this.dom.find(".lh-category-header__description",c).appendChild(a));return c}renderAuditGroup(a){const b=this.dom.createElement("div","lh-audit-group"),c=this.dom.createElement("div","lh-audit-group__header");this.dom.createChildOf(c,"span","lh-audit-group__title").textContent=a.title;a.description&&(a=this.dom.convertMarkdownLinkSnippets(a.description),a.classList.add("lh-audit-group__description"),c.appendChild(a));b.appendChild(c);
return b}_renderGroupedAudits(a,b){var c=new Map;c.set("NotAGroup",[]);for(var d of a){a=d.group||"NotAGroup";const e=c.get(a)||[];e.push(d);c.set(a,e)}d=[];for(const [e,f]of c)if("NotAGroup"===e)for(const g of f)d.push(this.renderAudit(g));else{c=b[e];c=this.renderAuditGroup(c);for(const g of f)c.appendChild(this.renderAudit(g));c.classList.add(`lh-audit-group--${e}`);d.push(c)}return d}renderUnexpandableClump(a,b){const c=this.dom.createElement("div");a=this._renderGroupedAudits(a,b);a.forEach(d=>
c.appendChild(d));return c}renderClump(a,{auditRefs:b,description:c}){var d=this.dom.cloneTemplate("#tmpl-lh-clump",this.templateContext);d=this.dom.find(".lh-clump",d);"warning"===a&&d.setAttribute("open","");var e=this.dom.find("div.lh-audit-group__summary",d);e.appendChild(this._createChevron());e=this.dom.find(".lh-audit-group__header",d);const f=this._clumpTitles[a];this.dom.find(".lh-audit-group__title",e).textContent=f;c&&(c=this.dom.convertMarkdownLinkSnippets(c),c.classList.add("lh-audit-group__description"),
e.appendChild(c));c=this.dom.find(".lh-audit-group__itemcount",d);c.textContent=`(${b.length})`;b=b.map(this.renderAudit.bind(this));d.append(...b);d.classList.add(`lh-clump--${a.toLowerCase()}`);return d}setTemplateContext(a){this.templateContext=a;this.detailsRenderer.setTemplateContext(a)}renderScoreGauge(a){const b=this.dom.cloneTemplate("#tmpl-lh-gauge",this.templateContext),c=this.dom.find("a.lh-gauge__wrapper",b);c.href=`#${a.id}`;Util.isPluginCategory(a.id)&&c.classList.add("lh-gauge__wrapper--plugin");
var d=Number(a.score),e=this.dom.find(".lh-gauge",b);(e=this.dom.find("circle.lh-gauge-arc",e))&&this._setGaugeArc(e,d);d=Math.round(100*d);e=this.dom.find("div.lh-gauge__percentage",b);e.textContent=d.toString();null===a.score&&(e.textContent="?",e.title=Util.i18n.strings.errorLabel);0===a.auditRefs.length||this.hasApplicableAudits(a)?c.classList.add(`lh-gauge__wrapper--${Util.calculateRating(a.score)}`):(c.classList.add("lh-gauge__wrapper--not-applicable"),e.textContent="-",e.title=Util.i18n.strings.notApplicableAuditsGroupTitle);
this.dom.find(".lh-gauge__label",b).textContent=a.title;return b}hasApplicableAudits(a){return a.auditRefs.some(b=>"notApplicable"!==b.result.scoreDisplayMode)}_setGaugeArc(a,b){const c=2*Math.PI*Number(a.getAttribute("r"));var d=Number(a.getAttribute("stroke-width"));const e=.25*d/c;a.style.transform=`rotate(${-90+360*e}deg)`;d=b*c-d/2;0===b&&(a.style.opacity="0");1===b&&(d=c);a.style.strokeDasharray=`${Math.max(d,0)} ${c}`}_auditHasWarning(a){return!(!a.result.warnings||!a.result.warnings.length)}_getClumpIdForAuditRef(a){const b=
a.result.scoreDisplayMode;return"manual"===b||"notApplicable"===b?b:Util.showAsPassed(a.result)?this._auditHasWarning(a)?"warning":"passed":"failed"}render(a,b={}){const c=this.dom.createElement("div","lh-category");this.createPermalinkSpan(c,a.id);c.appendChild(this.renderCategoryHeader(a,b));var d=new Map;d.set("failed",[]);d.set("warning",[]);d.set("manual",[]);d.set("passed",[]);d.set("notApplicable",[]);for(const e of a.auditRefs){const f=this._getClumpIdForAuditRef(e),g=d.get(f);g.push(e);d.set(f,
g)}for(const [e,f]of d)0!==f.length&&("failed"===e?(d=this.renderUnexpandableClump(f,b),d.classList.add("lh-clump--failed"),c.appendChild(d)):(d="manual"===e?a.manualDescription:void 0,d=this.renderClump(e,{auditRefs:f,description:d}),c.appendChild(d)));return c}createPermalinkSpan(a,b){a=this.dom.createChildOf(a,"span","lh-permalink");a.id=b}}"undefined"!==typeof module&&module.exports?module.exports=CategoryRenderer:self.CategoryRenderer=CategoryRenderer;class CriticalRequestChainRenderer{static initTree(a){var b=0;const c=Object.keys(a);0<c.length&&(b=a[c[0]],b=b.request.startTime);return{tree:a,startTime:b,transferSize:0}}static createSegment(a,b,c,d,e,f){const g=a[b];a=Object.keys(a);b=a.indexOf(b)===a.length-1;a=!!g.children&&0<Object.keys(g.children).length;e=Array.isArray(e)?e.slice(0):[];"undefined"!==typeof f&&e.push(!f);return{node:g,isLastChild:b,hasChildren:a,startTime:c,transferSize:d+g.request.transferSize,treeMarkers:e}}static createChainNode(a,
b,c,d){b=a.cloneTemplate("#tmpl-lh-crc__chains",b);a.find(".crc-node",b).setAttribute("title",c.node.request.url);const e=a.find(".crc-node__tree-marker",b);c.treeMarkers.forEach(g=>{g?e.appendChild(a.createElement("span","tree-marker vert")):e.appendChild(a.createElement("span","tree-marker"));e.appendChild(a.createElement("span","tree-marker"))});c.isLastChild?e.appendChild(a.createElement("span","tree-marker up-right")):e.appendChild(a.createElement("span","tree-marker vert-right"));e.appendChild(a.createElement("span",
"tree-marker right"));c.hasChildren?e.appendChild(a.createElement("span","tree-marker horiz-down")):e.appendChild(a.createElement("span","tree-marker right"));var f=c.node.request.url;f=d.renderTextURL(f);d=a.find(".crc-node__tree-value",b);d.appendChild(f);if(!c.hasChildren){const {startTime:g,endTime:h,transferSize:k}=c.node.request;c=a.createElement("span","crc-node__chain-duration");c.textContent=" - "+Util.i18n.formatMilliseconds(1E3*(h-g))+", ";f=a.createElement("span","crc-node__chain-duration");
f.textContent=Util.i18n.formatBytesToKiB(k,.01);d.appendChild(c);d.appendChild(f)}return b}static buildTree(a,b,c,d,e,f){d.appendChild(CriticalRequestChainRenderer.createChainNode(a,b,c,f));if(c.node.children)for(const g of Object.keys(c.node.children)){const h=CriticalRequestChainRenderer.createSegment(c.node.children,g,c.startTime,c.transferSize,c.treeMarkers,c.isLastChild);CriticalRequestChainRenderer.buildTree(a,b,h,d,e,f)}}static render(a,b,c,d){b=a.cloneTemplate("#tmpl-lh-crc",b);const e=a.find(".lh-crc",
b);a.find(".crc-initial-nav",b).textContent=Util.i18n.strings.crcInitialNavigation;a.find(".lh-crc__longest_duration_label",b).textContent=Util.i18n.strings.crcLongestDurationLabel;a.find(".lh-crc__longest_duration",b).textContent=Util.i18n.formatMilliseconds(c.longestChain.duration);const f=CriticalRequestChainRenderer.initTree(c.chains);for(const g of Object.keys(f.tree)){const h=CriticalRequestChainRenderer.createSegment(f.tree,g,f.startTime,f.transferSize);CriticalRequestChainRenderer.buildTree(a,
b,h,e,c,d)}return a.find(".lh-crc-container",b)}}"undefined"!==typeof module&&module.exports?module.exports=CriticalRequestChainRenderer:self.CriticalRequestChainRenderer=CriticalRequestChainRenderer;const URL_PREFIXES=["http://","https://","data:"];
class DetailsRenderer{constructor(a,b={}){this._dom=a;this._fullPageScreenshot=b.fullPageScreenshot}setTemplateContext(a){this._templateContext=a}render(a){switch(a.type){case "filmstrip":return this._renderFilmstrip(a);case "list":return this._renderList(a);case "table":return this._renderTable(a);case "criticalrequestchain":return CriticalRequestChainRenderer.render(this._dom,this._templateContext,a,this);case "opportunity":return this._renderTable(a);case "screenshot":case "debugdata":case "full-page-screenshot":case "treemap-data":return null;
default:return this._renderUnknown(a.type,a)}}_renderBytes(a){var b=Util.i18n.formatBytesToKiB(a.value,a.granularity);b=this._renderText(b);b.title=Util.i18n.formatBytes(a.value);return b}_renderMilliseconds(a){let b=Util.i18n.formatMilliseconds(a.value,a.granularity);"duration"===a.displayUnit&&(b=Util.i18n.formatDuration(a.value));return this._renderText(b)}renderTextURL(a){let b,c;try{var d=Util.parseURL(a);var e="/"===d.file?d.origin:d.file;b="/"===d.file||""===d.hostname?"":`(${d.hostname})`;
c=a}catch(f){e=a}d=this._dom.createElement("div","lh-text__url");d.appendChild(this._renderLink({text:e,url:a}));b&&(e=this._renderText(b),e.classList.add("lh-text__url-host"),d.appendChild(e));c&&(d.title=a,d.dataset.url=a);return d}_renderLink(a){var b=["https:","http:"];let c;try{c=new URL(a.url)}catch(d){}if(!c||!b.includes(c.protocol))return a=this._renderText(a.text),a.classList.add("lh-link"),a;b=this._dom.createElement("a");b.rel="noopener";b.target="_blank";b.textContent=a.text;b.href=c.href;
b.classList.add("lh-link");return b}_renderText(a){const b=this._dom.createElement("div","lh-text");b.textContent=a;return b}_renderNumeric(a){a=Util.i18n.formatNumber(a.value,a.granularity);const b=this._dom.createElement("div","lh-numeric");b.textContent=a;return b}_renderThumbnail(a){const b=this._dom.createElement("img","lh-thumbnail");b.src=a;b.title=a;b.alt="";return b}_renderUnknown(a,b){console.error(`Unknown details type: ${a}`,b);const c=this._dom.createElement("details","lh-unknown");this._dom.createChildOf(c,
"summary").textContent=`We don't know how to render audit details of type \`${a}\`. `+"The Lighthouse version that collected this data is likely newer than the Lighthouse version of the report renderer. Expand for the raw JSON.";this._dom.createChildOf(c,"pre").textContent=JSON.stringify(b,null,2);return c}_renderTableValue(a,b){if(void 0===a||null===a)return null;if("object"===typeof a)switch(a.type){case "code":return this._renderCode(a.value);case "link":return this._renderLink(a);case "node":return this.renderNode(a);
case "numeric":return this._renderNumeric(a);case "source-location":return this.renderSourceLocation(a);case "url":return this.renderTextURL(a.value);default:return this._renderUnknown(a.type,a)}switch(b.valueType){case "bytes":return a=Number(a),this._renderBytes({value:a,granularity:b.granularity});case "code":return b=String(a),this._renderCode(b);case "ms":return b={value:Number(a),granularity:b.granularity,displayUnit:b.displayUnit},this._renderMilliseconds(b);case "numeric":return a=Number(a),
this._renderNumeric({value:a,granularity:b.granularity});case "text":return b=String(a),this._renderText(b);case "thumbnail":return b=String(a),this._renderThumbnail(b);case "timespanMs":return b=Number(a),this._renderMilliseconds({value:b});case "url":const c=String(a);return URL_PREFIXES.some(d=>c.startsWith(d))?this.renderTextURL(c):this._renderCode(c);default:return this._renderUnknown(b.valueType,a)}}_getCanonicalizedHeadingsFromTable(a){return"opportunity"===a.type?a.headings:a.headings.map(b=>
this._getCanonicalizedHeading(b))}_getCanonicalizedHeading(a){let b;a.subItemsHeading&&(b=this._getCanonicalizedsubItemsHeading(a.subItemsHeading,a));return{key:a.key,valueType:a.itemType,subItemsHeading:b,label:a.text,displayUnit:a.displayUnit,granularity:a.granularity}}_getCanonicalizedsubItemsHeading(a,b){a.key||console.warn("key should not be null");return{key:a.key||"",valueType:a.itemType||b.itemType,granularity:a.granularity||b.granularity,displayUnit:a.displayUnit||b.displayUnit}}_getDerivedsubItemsHeading(a){return a.subItemsHeading?
{key:a.subItemsHeading.key||"",valueType:a.subItemsHeading.valueType||a.valueType,granularity:a.subItemsHeading.granularity||a.granularity,displayUnit:a.subItemsHeading.displayUnit||a.displayUnit,label:""}:null}_renderTableRow(a,b){const c=this._dom.createElement("tr");for(const d of b){if(!d||!d.key){this._dom.createChildOf(c,"td","lh-table-column--empty");continue}b=a[d.key];let e;void 0!==b&&null!==b&&(e=this._renderTableValue(b,d));e?(b=`lh-table-column--${d.valueType}`,this._dom.createChildOf(c,
"td",b).appendChild(e)):this._dom.createChildOf(c,"td","lh-table-column--empty")}return c}_renderTableRowsFromItem(a,b){const c=this._dom.createFragment();c.append(this._renderTableRow(a,b));if(!a.subItems)return c;b=b.map(this._getDerivedsubItemsHeading);if(!b.some(Boolean))return c;for(const d of a.subItems.items)a=this._renderTableRow(d,b),a.classList.add("lh-sub-item-row"),c.append(a);return c}_renderTable(a){if(!a.items.length)return this._dom.createElement("span");const b=this._dom.createElement("table",
"lh-table");var c=this._dom.createChildOf(b,"thead"),d=this._dom.createChildOf(c,"tr");c=this._getCanonicalizedHeadingsFromTable(a);for(var e of c){var f=e.valueType||"text";f=`lh-table-column--${f}`;const g=this._dom.createElement("div","lh-text");g.textContent=e.label;this._dom.createChildOf(d,"th",f).appendChild(g)}e=this._dom.createChildOf(b,"tbody");d=!0;for(const g of a.items){a=this._renderTableRowsFromItem(g,c);for(const h of this._dom.findAll("tr",a))h.classList.add(d?"lh-row--even":"lh-row--odd");
d=!d;e.append(a)}return b}_renderList(a){const b=this._dom.createElement("div","lh-list");a.items.forEach(c=>{c=SnippetRenderer.render(this._dom,this._templateContext,c,this);b.appendChild(c)});return b}renderNode(a){const b=this._dom.createElement("span","lh-node");if(a.nodeLabel){var c=this._dom.createElement("div");c.textContent=a.nodeLabel;b.appendChild(c)}a.snippet&&(c=this._dom.createElement("div"),c.classList.add("lh-node__snippet"),c.textContent=a.snippet,b.appendChild(c));a.selector&&(b.title=
a.selector);a.path&&b.setAttribute("data-path",a.path);a.selector&&b.setAttribute("data-selector",a.selector);a.snippet&&b.setAttribute("data-snippet",a.snippet);if(!this._fullPageScreenshot)return b;a=a.lhId&&this._fullPageScreenshot.nodes[a.lhId];if(!a||0===a.width||0===a.height)return b;c={width:147,height:100};(a=ElementScreenshotRenderer.render(this._dom,this._templateContext,this._fullPageScreenshot.screenshot,a,c))&&b.prepend(a);return b}renderSourceLocation(a){if(!a.url)return null;const b=
`${a.url}:${a.line+1}:${a.column}`;if(a.original){var c=a.original.file||"<unmapped>";c=`${c}:${a.original.line+1}:${a.original.column}`}if("network"===a.urlProvider&&c)c=this._renderLink({url:a.url,text:c}),c.title=`maps to generated location ${b}`;else if("network"!==a.urlProvider||c)if("comment"===a.urlProvider&&c)c=this._renderText(`${c} (from source map)`),c.title=`${b} (from sourceURL)`;else{if("comment"!==a.urlProvider||c)return null;c=this._renderText(`${b} (from sourceURL)`)}else c=this.renderTextURL(a.url),
this._dom.find(".lh-link",c).textContent+=`:${a.line+1}:${a.column}`;c.classList.add("lh-source-location");c.setAttribute("data-source-url",a.url);c.setAttribute("data-source-line",String(a.line));c.setAttribute("data-source-column",String(a.column));return c}_renderFilmstrip(a){const b=this._dom.createElement("div","lh-filmstrip");for(const c of a.items)a=this._dom.createChildOf(b,"div","lh-filmstrip__frame"),this._dom.createChildOf(a,"img","lh-filmstrip__thumbnail",{src:c.data,alt:"Screenshot"});
return b}_renderCode(a){const b=this._dom.createElement("pre","lh-code");b.textContent=a;return b}}"undefined"!==typeof module&&module.exports?module.exports=DetailsRenderer:self.DetailsRenderer=DetailsRenderer;class DOM{constructor(a){this._document=a;this._lighthouseChannel="unknown"}createElement(a,b,c={}){const d=this._document.createElement(a);b&&(d.className=b);Object.keys(c).forEach(e=>{const f=c[e];"undefined"!==typeof f&&d.setAttribute(e,f)});return d}createElementNS(a,b,c,d={}){const e=this._document.createElementNS(a,b);c&&(e.className=c);Object.keys(d).forEach(f=>{const g=d[f];"undefined"!==typeof g&&e.setAttribute(f,g)});return e}createFragment(){return this._document.createDocumentFragment()}createChildOf(a,
b,c,d){b=this.createElement(b,c,d);a.appendChild(b);return b}cloneTemplate(a,b){b=b.querySelector(a);if(!b)throw Error(`Template not found: template${a}`);a=this._document.importNode(b.content,!0);b.hasAttribute("data-stamped")&&this.findAll("style",a).forEach(c=>c.remove());b.setAttribute("data-stamped","true");return a}resetTemplates(){this.findAll("template[data-stamped]",this._document).forEach(a=>{a.removeAttribute("data-stamped")})}convertMarkdownLinkSnippets(a){const b=this.createElement("span");
for(const d of Util.splitMarkdownLink(a))if(d.isLink){a=new URL(d.linkHref);var c=["https://developers.google.com","https://web.dev"];c.includes(a.origin)&&(a.searchParams.set("utm_source","lighthouse"),a.searchParams.set("utm_medium",this._lighthouseChannel));c=this.createElement("a");c.rel="noopener";c.target="_blank";c.textContent=d.text;c.href=a.href;b.appendChild(c)}else b.appendChild(this._document.createTextNode(d.text));return b}convertMarkdownCodeSnippets(a){const b=this.createElement("span");
for(const c of Util.splitMarkdownCodeSpans(a))c.isCode?(a=this.createElement("code"),a.textContent=c.text,b.appendChild(a)):b.appendChild(this._document.createTextNode(c.text));return b}document(){return this._document}isDevTools(){return!!this._document.querySelector(".lh-devtools")}find(a,b){b=b.querySelector(a);if(null===b)throw Error(`query ${a} not found`);return b}findAll(a,b){return a=Array.from(b.querySelectorAll(a))}}
"undefined"!==typeof module&&module.exports?module.exports=DOM:self.DOM=DOM;/*
 Copyright 2020 The Lighthouse Authors. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/
class ElementScreenshotRenderer{static getScreenshotPositions(a,b,c){var d={x:a.left+a.width/2,y:a.top+a.height/2};var e=d.x-b.width/2;var f=c.width-b.width;e=0>e?0:e>f?f:e;d=d.y-b.height/2;b=c.height-b.height;b=0>d?0:d>b?b:d;return{screenshot:{left:e,top:b},clip:{left:a.left-e,top:a.top-b}}}static renderClipPathInScreenshot(a,b,c,d,e){const f=a.find("clipPath",b);var g=`clip-${Util.getUniqueSuffix()}`;f.id=g;b.style.clipPath=`url(#${g})`;b=c.top/e.height;g=b+d.height/e.height;c=c.left/e.width;d=
c+d.width/e.width;d=[`0,0             1,0            1,${b}          0,${b}`,`0,${g}     1,${g}    1,1               0,1`,`0,${b}        ${c},${b} ${c},${g} 0,${g}`,`${d},${b} 1,${b}       1,${g}       ${d},${g}`];for(const h of d)f.append(a.createElementNS("http://www.w3.org/2000/svg","polygon",void 0,{points:h}))}static installFullPageScreenshot(a,b){a.style.setProperty("--element-screenshot-url",`url(${b.data})`)}static installOverlayFeature(a){const {dom:b,reportEl:c,overlayContainerEl:d,templateContext:e,
fullPageScreenshot:f}=a;c.classList.contains("lh-screenshot-overlay--enabled")||(c.classList.add("lh-screenshot-overlay--enabled"),c.addEventListener("click",g=>{if(g=g.target){var h=g.closest(".lh-node > .lh-element-screenshot");if(h){var k=b.createElement("div","lh-element-screenshot__overlay");d.append(k);g={width:.95*k.clientWidth,height:.8*k.clientHeight};h={width:Number(h.dataset.rectWidth),height:Number(h.dataset.rectHeight),left:Number(h.dataset.rectLeft),right:Number(h.dataset.rectLeft)+
Number(h.dataset.rectWidth),top:Number(h.dataset.rectTop),bottom:Number(h.dataset.rectTop)+Number(h.dataset.rectHeight)};(g=ElementScreenshotRenderer.render(b,e,f.screenshot,h,g))?(k.appendChild(g),k.addEventListener("click",()=>k.remove())):k.remove()}}}))}static _computeZoomFactor(a,b){a={x:b.width/a.width,y:b.height/a.height};a=.75*Math.min(a.x,a.y);return Math.min(1,a)}static render(a,b,c,d,e){if(!(d.left<=c.width&&0<=d.right&&d.top<=c.height&&0<=d.bottom))return null;b=a.cloneTemplate("#tmpl-lh-element-screenshot",
b);b=a.find("div.lh-element-screenshot",b);b.dataset.rectWidth=d.width.toString();b.dataset.rectHeight=d.height.toString();b.dataset.rectLeft=d.left.toString();b.dataset.rectTop=d.top.toString();const f=this._computeZoomFactor(d,e);e={width:e.width/f,height:e.height/f};e.width=Math.min(c.width,e.width);const g={width:e.width*f,height:e.height*f},h=ElementScreenshotRenderer.getScreenshotPositions(d,e,{width:c.width,height:c.height});var k=a.find("div.lh-element-screenshot__content",b);k.style.top=
`-${g.height}px`;k=a.find("div.lh-element-screenshot__image",b);k.style.width=g.width+"px";k.style.height=g.height+"px";k.style.backgroundPositionY=-(h.screenshot.top*f)+"px";k.style.backgroundPositionX=-(h.screenshot.left*f)+"px";k.style.backgroundSize=`${c.width*f}px ${c.height*f}px`;c=a.find("div.lh-element-screenshot__element-marker",b);c.style.width=d.width*f+"px";c.style.height=d.height*f+"px";c.style.left=h.clip.left*f+"px";c.style.top=h.clip.top*f+"px";c=a.find("div.lh-element-screenshot__mask",
b);c.style.width=g.width+"px";c.style.height=g.height+"px";ElementScreenshotRenderer.renderClipPathInScreenshot(a,c,h.clip,d,e);return b}}"undefined"!==typeof module&&module.exports?module.exports=ElementScreenshotRenderer:self.ElementScreenshotRenderer=ElementScreenshotRenderer;class I18n{constructor(a,b){"en-XA"===a&&(a="de");this._numberDateLocale=a;this._numberFormatter=new Intl.NumberFormat(a);this._percentFormatter=new Intl.NumberFormat(a,{style:"percent"});this._strings=b}get strings(){return this._strings}formatNumber(a,b){b=void 0===b?.1:b;a=Math.round(a/b)*b;return this._numberFormatter.format(a)}formatBytesToKiB(a,b){b=void 0===b?.1:b;const c=this._byteFormatterForGranularity(b);a=c.format(Math.round(a/1024/b)*b);return`${a}${"\u00a0"}KiB`}formatBytes(a,b){b=void 0===
b?1:b;const c=this._byteFormatterForGranularity(b);a=c.format(Math.round(a/b)*b);return`${a}${"\u00a0"}bytes`}_byteFormatterForGranularity(a){let b=0;1>a&&(b=-Math.floor(Math.log10(a)));return new Intl.NumberFormat(this._numberDateLocale,Object.assign({},this._numberFormatter.resolvedOptions(),{maximumFractionDigits:b,minimumFractionDigits:b}))}formatMilliseconds(a,b){b=void 0===b?10:b;a=Math.round(a/b)*b;return 0===a?`${this._numberFormatter.format(0)}${"\u00a0"}ms`:`${this._numberFormatter.format(a)}${"\u00a0"}ms`}formatSeconds(a,
b){b=void 0===b?.1:b;a=Math.round(a/1E3/b)*b;return`${this._numberFormatter.format(a)}${"\u00a0"}s`}formatDateTime(a){const b={month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"numeric",timeZoneName:"short"};let c;try{c=new Intl.DateTimeFormat(this._numberDateLocale,b)}catch(d){b.timeZone="UTC",c=new Intl.DateTimeFormat(this._numberDateLocale,b)}return c.format(new Date(a))}formatDuration(a){let b=a/1E3;if(0===Math.round(b))return"None";const c=[],d={d:86400,h:3600,m:60,s:1};Object.keys(d).forEach(e=>
{const f=d[e],g=Math.floor(b/f);0<g&&(b-=g*f,c.push(`${g}\xa0${e}`))});return c.join(" ")}}"undefined"!==typeof module&&module.exports?module.exports=I18n:self.I18n=I18n;/*

 Copyright 2018 The Lighthouse Authors. All Rights Reserved.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS-IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
class PerformanceCategoryRenderer extends CategoryRenderer{_renderMetric(a){var b=this.dom.cloneTemplate("#tmpl-lh-metric",this.templateContext);const c=this.dom.find(".lh-metric",b);c.id=a.result.id;var d=Util.calculateRating(a.result.score,a.result.scoreDisplayMode);c.classList.add(`lh-metric--${d}`);d=this.dom.find(".lh-metric__title",b);d.textContent=a.result.title;d=this.dom.find(".lh-metric__value",b);d.textContent=a.result.displayValue||"";b=this.dom.find(".lh-metric__description",b);b.appendChild(this.dom.convertMarkdownLinkSnippets(a.result.description));
"error"===a.result.scoreDisplayMode&&(b.textContent="",d.textContent="Error!",b=this.dom.createChildOf(b,"span"),b.textContent=a.result.errorMessage||"Report error: no metric information");return c}_renderOpportunity(a,b){var c=this.dom.cloneTemplate("#tmpl-lh-opportunity",this.templateContext);c=this.populateAuditValues(a,c);c.id=a.result.id;if(!a.result.details||"error"===a.result.scoreDisplayMode)return c;const d=a.result.details;if("opportunity"!==d.type)return c;const e=this.dom.find("span.lh-audit__display-text, div.lh-audit__display-text",
c);b=`${d.overallSavingsMs/b*100}%`;this.dom.find("div.lh-sparkline__bar",c).style.width=b;e.textContent=Util.i18n.formatSeconds(d.overallSavingsMs,.01);a.result.displayValue&&(a=a.result.displayValue,this.dom.find("div.lh-load-opportunity__sparkline",c).title=a,e.title=a);return c}_getWastedMs(a){if(a.result.details&&"opportunity"===a.result.details.type){a=a.result.details;if("number"!==typeof a.overallSavingsMs)throw Error("non-opportunity details passed to _getWastedMs");return a.overallSavingsMs}return Number.MIN_VALUE}_getScoringCalculatorHref(a){var b=
a.filter(d=>"metrics"===d.group),c=a.find(d=>"first-cpu-idle"===d.id);a=a.find(d=>"first-meaningful-paint"===d.id);c&&b.push(c);a&&b.push(a);b=b.map(d=>{let e;"number"===typeof d.result.numericValue?(e="cumulative-layout-shift"===d.id?Math.round(100*d.result.numericValue)/100:Math.round(d.result.numericValue),e=e.toString()):e="null";return[d.acronym||d.id,e]});b=[...b];Util.reportJson&&(b.push(["device",Util.reportJson.configSettings.formFactor]),b.push(["version",Util.reportJson.lighthouseVersion]));
b=new URLSearchParams(b);c=new URL("https://googlechrome.github.io/lighthouse/scorecalc/");c.hash=b.toString();return c.href}render(a,b,c){var d=Util.i18n.strings;const e=this.dom.createElement("div","lh-category");"PSI"===c?(c=this.dom.createElement("div","lh-score__gauge"),c.appendChild(this.renderScoreGauge(a,b)),e.appendChild(c)):(this.createPermalinkSpan(e,a.id),e.appendChild(this.renderCategoryHeader(a,b)));var f=this.renderAuditGroup(b.metrics);c=this.dom.cloneTemplate("#tmpl-lh-metrics-toggle",
this.templateContext);const g=this.dom.find(".lh-metrics-toggle",c);f.append(...g.childNodes);c=a.auditRefs.filter(l=>"metrics"===l.group);const h=this.dom.createChildOf(f,"div","lh-metrics-container");c.forEach(l=>{h.appendChild(this._renderMetric(l))});var k=this.dom.createChildOf(f,"div","lh-metrics__disclaimer");const p=this.dom.convertMarkdownLinkSnippets(d.varianceDisclaimer);k.appendChild(p);k=this.dom.createChildOf(k,"a","lh-calclink");k.target="_blank";k.textContent=d.calculatorLink;k.href=
this._getScoringCalculatorHref(a.auditRefs);f.classList.add("lh-audit-group--metrics");e.appendChild(f);f=this.dom.createChildOf(e,"div","lh-filmstrip-container");(k=(k=a.auditRefs.find(l=>"screenshot-thumbnails"===l.id))&&k.result)&&k.details&&(f.id=k.id,(k=this.detailsRenderer.render(k.details))&&f.appendChild(k));f=a.auditRefs.filter(l=>"load-opportunities"===l.group&&!Util.showAsPassed(l.result)).sort((l,m)=>this._getWastedMs(m)-this._getWastedMs(l));c=c.filter(l=>!!l.relevantAudits);c.length&&
this.renderMetricAuditFilter(c,e);if(f.length){c=f.map(q=>this._getWastedMs(q));c=Math.max(...c);const l=Math.max(1E3*Math.ceil(c/1E3),2E3),m=this.renderAuditGroup(b["load-opportunities"]);c=this.dom.cloneTemplate("#tmpl-lh-opportunity-header",this.templateContext);this.dom.find(".lh-load-opportunity__col--one",c).textContent=d.opportunityResourceColumnLabel;this.dom.find(".lh-load-opportunity__col--two",c).textContent=d.opportunitySavingsColumnLabel;d=this.dom.find(".lh-load-opportunity__header",
c);m.appendChild(d);f.forEach(q=>m.appendChild(this._renderOpportunity(q,l)));m.classList.add("lh-audit-group--load-opportunities");e.appendChild(m)}d=a.auditRefs.filter(l=>"diagnostics"===l.group&&!Util.showAsPassed(l.result)).sort((l,m)=>{l="informative"===l.result.scoreDisplayMode?100:Number(l.result.score);m="informative"===m.result.scoreDisplayMode?100:Number(m.result.score);return l-m});if(d.length){const l=this.renderAuditGroup(b.diagnostics);d.forEach(m=>l.appendChild(this.renderAudit(m)));
l.classList.add("lh-audit-group--diagnostics");e.appendChild(l)}d=a.auditRefs.filter(l=>("load-opportunities"===l.group||"diagnostics"===l.group)&&Util.showAsPassed(l.result));if(!d.length)return e;d={auditRefs:d,groupDefinitions:b};d=this.renderClump("passed",d);e.appendChild(d);const n=[];["performance-budget","timing-budget"].forEach(l=>{var m=a.auditRefs.find(q=>q.id===l);m&&m.result.details&&(m=this.detailsRenderer.render(m.result.details))&&(m.id=l,m.classList.add("lh-audit"),n.push(m))});if(0<
n.length){const l=this.renderAuditGroup(b.budgets);n.forEach(m=>l.appendChild(m));l.classList.add("lh-audit-group--budgets");e.appendChild(l)}return e}renderMetricAuditFilter(a,b){const c=this.dom.createElement("div","lh-metricfilter");var d=this.dom.createChildOf(c,"span","lh-metricfilter__text");d.textContent=Util.i18n.strings.showRelevantAudits;a=[{acronym:"All"},...a];for(const e of a){const f=`metric-${e.acronym}`;a=this.dom.createChildOf(c,"input","lh-metricfilter__radio",{type:"radio",name:"metricsfilter",
id:f});d=this.dom.createChildOf(c,"label","lh-metricfilter__label",{for:f,title:e.result&&e.result.title});d.textContent=e.acronym||e.id;"All"===e.acronym&&(a.checked=!0,d.classList.add("lh-metricfilter__label--active"));b.append(c);a.addEventListener("input",()=>{for(var g of b.querySelectorAll("label.lh-metricfilter__label"))g.classList.toggle("lh-metricfilter__label--active",g.htmlFor===f);b.classList.toggle("lh-category--filtered","All"!==e.acronym);for(const h of b.querySelectorAll("div.lh-audit"))"All"===
e.acronym?h.hidden=!1:(h.hidden=!0,e.relevantAudits&&e.relevantAudits.includes(h.id)&&(h.hidden=!1));g=b.querySelectorAll("div.lh-audit-group, details.lh-audit-group");for(const h of g)h.hidden=!1,g=Array.from(h.querySelectorAll("div.lh-audit")),g=!!g.length&&g.every(k=>k.hidden),h.hidden=g})}}}"undefined"!==typeof module&&module.exports?module.exports=PerformanceCategoryRenderer:self.PerformanceCategoryRenderer=PerformanceCategoryRenderer;function prepareLabData(a,b){const c="string"===typeof a?JSON.parse(a):a,d=new DOM(b);d.resetTemplates();a=Util.prepareReportResult(c);var e=new I18n(a.configSettings.locale,Object.assign({},Util.UIStrings,a.i18n.rendererFormattedStrings));Util.i18n=e;Util.reportJson=a;var f=a.categories.performance;if(!f)throw Error("No performance category. Can't make lab data section");if(!a.categoryGroups)throw Error("No category groups found.");a.categoryGroups.metrics.title=Util.i18n.strings.labDataTitle;a.categoryGroups.metrics.description=
Util.i18n.strings.lsPerformanceCategoryDescription;const g=a.audits["full-page-screenshot"]&&a.audits["full-page-screenshot"].details&&"full-page-screenshot"===a.audits["full-page-screenshot"].details.type?a.audits["full-page-screenshot"].details:void 0;e=new DetailsRenderer(d,{fullPageScreenshot:g});e=new PerformanceCategoryRenderer(d,e);a=e.render(f,a.categoryGroups,"PSI");e=d.find(".lh-score__gauge",a);e.remove();var h=d.find(".lh-gauge__wrapper",e);h.classList.add("lh-gauge__wrapper--huge");h.removeAttribute("href");
f=_getFinalScreenshot(f);h=d.cloneTemplate("#tmpl-lh-scorescale",d.document());h=d.find(".lh-scorescale",h);const k=new ReportUIFeatures(d);k.json=c;const p=n=>{if(g){ElementScreenshotRenderer.installFullPageScreenshot(n,g.screenshot);var l=b.querySelector(".element-screenshots-container");if(!l)throw Error("missing .element-screenshots-container");const m=b.createElement("div");l.append(m);ElementScreenshotRenderer.installOverlayFeature({dom:d,reportEl:n,overlayContainerEl:m,templateContext:b,fullPageScreenshot:g});
ElementScreenshotRenderer.installFullPageScreenshot(m,g.screenshot)}(l=c.audits["script-treemap-data"]&&c.audits["script-treemap-data"].details)&&k.addButton({container:n.querySelector(".lh-audit-group--metrics"),text:Util.i18n.strings.viewTreemapLabel,icon:"treemap",onClick:()=>ReportUIFeatures.openTreemap(c)})};return{scoreGaugeEl:e,perfCategoryEl:a,finalScreenshotDataUri:f,scoreScaleEl:h,installFeatures:p}}
function _getFinalScreenshot(a){a=a.auditRefs.find(b=>"final-screenshot"===b.id);return a&&a.result&&"error"!==a.result.scoreDisplayMode?(a=a.result.details)&&"screenshot"===a.type?a.data:null:null}"undefined"!==typeof module&&module.exports?module.exports=prepareLabData:self.prepareLabData=prepareLabData;class PwaCategoryRenderer extends CategoryRenderer{render(a,b={}){const c=this.dom.createElement("div","lh-category");this.createPermalinkSpan(c,a.id);c.appendChild(this.renderCategoryHeader(a,b));var d=a.auditRefs;const e=d.filter(f=>"manual"!==f.result.scoreDisplayMode);b=this._renderAudits(e,b);c.appendChild(b);d=d.filter(f=>"manual"===f.result.scoreDisplayMode);a=this.renderClump("manual",{auditRefs:d,description:a.manualDescription});c.appendChild(a);return c}renderScoreGauge(a,b){if(null===
a.score)return super.renderScoreGauge(a,b);const c=this.dom.cloneTemplate("#tmpl-lh-gauge--pwa",this.templateContext),d=this.dom.find("a.lh-gauge--pwa__wrapper",c);d.href=`#${a.id}`;var e=c.querySelector("svg");if(!e)throw Error("no SVG element found in PWA score gauge template");PwaCategoryRenderer._makeSvgReferencesUnique(e);e=this._getGroupIds(a.auditRefs);const f=this._getPassingGroupIds(a.auditRefs);if(f.size===e.size)d.classList.add("lh-badged--all");else for(const g of f)d.classList.add(`lh-badged--${g}`);
this.dom.find(".lh-gauge__label",c).textContent=a.title;d.title=this._getGaugeTooltip(a.auditRefs,b);return c}_getGroupIds(a){a=a.map(b=>b.group).filter(b=>!!b);return new Set(a)}_getPassingGroupIds(a){const b=this._getGroupIds(a);for(const c of a)!Util.showAsPassed(c.result)&&c.group&&b.delete(c.group);return b}_getGaugeTooltip(a,b){var c=this._getGroupIds(a);const d=[];for(const f of c){var e=a.filter(h=>h.group===f);c=e.length;e=e.filter(h=>Util.showAsPassed(h.result)).length;const g=b[f].title;
d.push(`${g}: ${e}/${c}`)}return d.join(", ")}_renderAudits(a,b){b=this.renderUnexpandableClump(a,b);a=this._getPassingGroupIds(a);for(const c of a)a=this.dom.find(`.lh-audit-group--${c}`,b),a.classList.add("lh-badged");return b}static _makeSvgReferencesUnique(a){var b=a.querySelector("defs");if(b){var c=Util.getUniqueSuffix();b=b.querySelectorAll("[id]");for(const e of b){var d=e.id;b=`${d}-${c}`;e.id=b;const f=a.querySelectorAll(`use[href="#${d}"]`);for(const g of f)g.setAttribute("href",`#${b}`);
d=a.querySelectorAll(`[fill="url(#${d})"]`);for(const g of d)g.setAttribute("fill",`url(#${b})`)}}}}"undefined"!==typeof module&&module.exports?module.exports=PwaCategoryRenderer:self.PwaCategoryRenderer=PwaCategoryRenderer;class ReportRenderer{constructor(a){this._dom=a;this._templateContext=this._dom.document()}setTemplateContext(a){this._templateContext=a}_renderReportTopbar(a){const b=this._dom.cloneTemplate("#tmpl-lh-topbar",this._templateContext),c=this._dom.find("a.lh-topbar__url",b);c.href=c.textContent=a.finalUrl;c.title=a.finalUrl;return b}_renderReportHeader(){const a=this._dom.cloneTemplate("#tmpl-lh-heading",this._templateContext),b=this._dom.cloneTemplate("#tmpl-lh-scores-wrapper",this._templateContext),
c=this._dom.find(".lh-scores-wrapper-placeholder",a);c.replaceWith(b);return a}_renderReportFooter(a){const b=this._dom.cloneTemplate("#tmpl-lh-footer",this._templateContext),c=this._dom.find(".lh-env__items",b);c.id="runtime-settings";this._dom.find(".lh-env__title",b).textContent=Util.i18n.strings.runtimeSettingsTitle;var d=Util.getEnvironmentDisplayValues(a.configSettings||{});d=[{name:Util.i18n.strings.runtimeSettingsUrl,description:a.finalUrl},{name:Util.i18n.strings.runtimeSettingsFetchTime,
description:Util.i18n.formatDateTime(a.fetchTime)},...d,{name:Util.i18n.strings.runtimeSettingsChannel,description:a.configSettings.channel},{name:Util.i18n.strings.runtimeSettingsUA,description:a.userAgent},{name:Util.i18n.strings.runtimeSettingsUANetwork,description:a.environment&&a.environment.networkUserAgent},{name:Util.i18n.strings.runtimeSettingsBenchmark,description:a.environment&&a.environment.benchmarkIndex.toFixed(0)}];a.environment.credits&&a.environment.credits["axe-core"]&&d.push({name:Util.i18n.strings.runtimeSettingsAxeVersion,
description:a.environment.credits["axe-core"]});for(const e of d)e.description&&(d=this._dom.cloneTemplate("#tmpl-lh-env__items",c),this._dom.find(".lh-env__name",d).textContent=e.name,this._dom.find(".lh-env__description",d).textContent=e.description,c.appendChild(d));this._dom.find(".lh-footer__version_issue",b).textContent=Util.i18n.strings.footerIssue;this._dom.find(".lh-footer__version",b).textContent=a.lighthouseVersion;return b}_renderReportWarnings(a){if(!a.runWarnings||0===a.runWarnings.length)return this._dom.createElement("div");
const b=this._dom.cloneTemplate("#tmpl-lh-warnings--toplevel",this._templateContext);var c=this._dom.find(".lh-warnings__msg",b);c.textContent=Util.i18n.strings.toplevelWarningsMessage;c=this._dom.find("ul",b);for(const d of a.runWarnings)a=c.appendChild(this._dom.createElement("li")),a.appendChild(this._dom.convertMarkdownLinkSnippets(d));return b}_renderScoreGauges(a,b,c){const d=[],e=[],f=[];for(const g of Object.values(a.categories)){const h=c[g.id]||b,k=h.renderScoreGauge(g,a.categoryGroups||
{});Util.isPluginCategory(g.id)?f.push(k):h.renderScoreGauge===b.renderScoreGauge?d.push(k):e.push(k)}return[...d,...e,...f]}_renderReport(a){var b=new I18n(a.configSettings.locale,Object.assign({},Util.UIStrings,a.i18n.rendererFormattedStrings));Util.i18n=b;Util.reportJson=a;b=a.audits["full-page-screenshot"]&&a.audits["full-page-screenshot"].details&&"full-page-screenshot"===a.audits["full-page-screenshot"].details.type?a.audits["full-page-screenshot"].details:void 0;var c=new DetailsRenderer(this._dom,
{fullPageScreenshot:b}),d=new CategoryRenderer(this._dom,c);d.setTemplateContext(this._templateContext);const e={performance:new PerformanceCategoryRenderer(this._dom,c),pwa:new PwaCategoryRenderer(this._dom,c)};Object.values(e).forEach(l=>{l.setTemplateContext(this._templateContext)});c=this._dom.createElement("div");c.appendChild(this._renderReportHeader());const f=this._dom.createElement("div","lh-container"),g=this._dom.createElement("div","lh-report");g.appendChild(this._renderReportWarnings(a));
var h,k=1===Object.keys(a.categories).length;k?c.classList.add("lh-header--solo-category"):h=this._dom.createElement("div","lh-scores-header");if(h){k=this._dom.cloneTemplate("#tmpl-lh-scorescale",this._templateContext);var p=this._dom.find(".lh-scores-container",c);h.append(...this._renderScoreGauges(a,d,e));p.appendChild(h);p.appendChild(k);h=this._dom.createElement("div","lh-sticky-header");h.append(...this._renderScoreGauges(a,d,e));f.appendChild(h)}h=g.appendChild(this._dom.createElement("div",
"lh-categories"));for(var n of Object.values(a.categories))k=e[n.id]||d,p=k.dom.createChildOf(h,"div","lh-category-wrapper"),p.appendChild(k.render(n,a.categoryGroups));n=this._dom.createFragment();d=this._renderReportTopbar(a);n.appendChild(d);n.appendChild(f);f.appendChild(c);f.appendChild(g);g.appendChild(this._renderReportFooter(a));b&&ElementScreenshotRenderer.installFullPageScreenshot(f,b.screenshot);return n}}
"undefined"!==typeof module&&module.exports?module.exports=ReportRenderer:self.ReportRenderer=ReportRenderer;class ReportUIFeatures{constructor(a){this._dom=a;this._document=this._dom.document();this._templateContext=this._dom.document();this._dropDown=new DropDown(this._dom);this._copyAttempt=!1;this.onMediaQueryChange=this.onMediaQueryChange.bind(this);this.collapseAllDetails=this.collapseAllDetails.bind(this);this.expandAllDetails=this.expandAllDetails.bind(this);this._toggleDarkTheme=this._toggleDarkTheme.bind(this);this._updateStickyHeaderOnScroll=this._updateStickyHeaderOnScroll.bind(this)}setTemplateContext(a){this._templateContext=
a}addButton(a){var b=this._document.querySelector(".lh-audit-group--metrics"),c=a.container||b;if(c)return(b=c.querySelector(".lh-buttons"))||(b=this._dom.createChildOf(c,"div","lh-buttons")),c=["lh-button"],a.icon&&(c.push("report-icon"),c.push(`report-icon--${a.icon}`)),b=this._dom.createChildOf(b,"button",c.join(" ")),b.textContent=a.text,b.addEventListener("click",a.onClick),b}_getScrollParent(a){var {overflowY:b}=window.getComputedStyle(a);return(b="visible"!==b&&"hidden"!==b)?a:a.parentElement?
this._getScrollParent(a.parentElement):document}_enableFireworks(){const a=this._dom.find(".lh-scores-container",this._document);a.classList.add("score100");a.addEventListener("click",()=>{a.classList.toggle("fireworks-paused")})}_fireEventOn(a,b=this._document,c){a=new CustomEvent(a,c?{detail:c}:void 0);b.dispatchEvent(a)}_setupMediaQueryListeners(){const a=self.matchMedia("(max-width: 500px)");a.addListener(this.onMediaQueryChange);this.onMediaQueryChange(a)}onMediaQueryChange(a){const b=this._dom.find(".lh-root",
this._document);b.classList.toggle("lh-narrow",a.matches)}_setupThirdPartyFilter(){const a=["uses-rel-preconnect","third-party-facades"],b=["legacy-javascript"];var c=Array.from(this._document.querySelectorAll("table.lh-table"));c=c.filter(d=>d.querySelector("td.lh-table-column--url, td.lh-table-column--source-location")).filter(d=>{d=d.closest(".lh-audit");if(!d)throw Error(".lh-table not within audit");return!a.includes(d.id)});c.forEach((d,e)=>{const f=Array.from(d.tBodies[0].rows),g=this._getThirdPartyRows(f,
this.json.finalUrl),h=this._dom.cloneTemplate("#tmpl-lh-3p-filter",this._templateContext),k=this._dom.find("input",h);e=`lh-3p-filter-label--${e}`;k.id=e;k.addEventListener("change",n=>{n=n.target instanceof HTMLInputElement&&!n.target.checked;let l=!0,m=f[0];for(;m;){const q=n&&g.includes(m);do m.classList.toggle("lh-row--hidden",q),m.classList.toggle("lh-row--even",!q&&l),m.classList.toggle("lh-row--odd",!q&&!l),m=m.nextElementSibling;while(m&&m.classList.contains("lh-sub-item-row"));q||(l=!l)}});
this._dom.find("label",h).setAttribute("for",e);this._dom.find(".lh-3p-filter-count",h).textContent=`${g.length}`;this._dom.find(".lh-3p-ui-string",h).textContent=Util.i18n.strings.thirdPartyResourcesLabel;e=g.length===f.length;const p=!g.length;if(e||p)k.disabled=!0,k.checked=e;if(d.parentNode){d.parentNode.insertBefore(h,d);d=d.closest(".lh-audit");if(!d)throw Error(".lh-table not within audit");b.includes(d.id)&&!e&&k.click()}})}_setupElementScreenshotOverlay(a){const b=this.json.audits["full-page-screenshot"]&&
this.json.audits["full-page-screenshot"].details&&"full-page-screenshot"===this.json.audits["full-page-screenshot"].details.type&&this.json.audits["full-page-screenshot"].details;b&&ElementScreenshotRenderer.installOverlayFeature({dom:this._dom,reportEl:a,overlayContainerEl:a,templateContext:this._templateContext,fullPageScreenshot:b})}_getThirdPartyRows(a,b){const c=[];b=Util.getRootDomain(b);for(const d of a)d.classList.contains("lh-sub-item-row")||(a=d.querySelector("div.lh-text__url"))&&(a=a.dataset.url)&&
(a=Util.getRootDomain(a)!==b)&&c.push(d);return c}_setupStickyHeaderElements(){this.topbarEl=this._dom.find("div.lh-topbar",this._document);this.scoreScaleEl=this._dom.find("div.lh-scorescale",this._document);this.stickyHeaderEl=this._dom.find("div.lh-sticky-header",this._document);this.highlightEl=this._dom.createChildOf(this.stickyHeaderEl,"div","lh-highlighter")}_resetUIState(){this._dropDown.close();this._dom.resetTemplates()}_print(){self.print()}static computeWindowNameSuffix(a){var b=a.generatedTime;
b=a.fetchTime||b;return`${a.lighthouseVersion}-${a.requestedUrl}-${b}`}static openTreemap(a){var b=a.audits["script-treemap-data"].details;if(!b)throw Error("no script treemap data found");b={lhr:{requestedUrl:a.requestedUrl,finalUrl:a.finalUrl,audits:{"script-treemap-data":a.audits["script-treemap-data"]},configSettings:{locale:a.configSettings.locale}}};var c=window.location.host.endsWith(".vercel.app");const d=(new URLSearchParams(window.location.search)).has("dev");c=c?`https://${window.location.host}/gh-pages`:
d?"http://localhost:8000":"https://googlechrome.github.io/lighthouse";c+="/treemap/";a="treemap-"+this.computeWindowNameSuffix(a);ReportUIFeatures.openTabWithUrlData(b,c,a)}static async openTabWithUrlData(a,b,c){b=new URL(b);const d=!!window.CompressionStream;b.hash=await TextEncoding.toBase64(JSON.stringify(a),{gzip:d});d&&b.searchParams.set("gzip","1");window.open(b.toString(),c)}expandAllDetails(){const a=this._dom.findAll(".lh-categories details",this._document);a.map(b=>b.open=!0)}collapseAllDetails(){const a=
this._dom.findAll(".lh-categories details",this._document);a.map(b=>b.open=!1)}_setUpCollapseDetailsAfterPrinting(){"onbeforeprint"in self?self.addEventListener("afterprint",this.collapseAllDetails):self.matchMedia("print").addListener(a=>{a.matches?this.expandAllDetails():this.collapseAllDetails()})}_saveFile(a){const b=getFilenamePrefix({finalUrl:this.json.finalUrl,fetchTime:this.json.fetchTime}),c=a.type.match("json")?".json":".html",d=URL.createObjectURL(a);a=this._dom.createElement("a");a.download=
`${b}${c}`;a.href=d;this._document.body.appendChild(a);a.click();this._document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(d),500)}_toggleDarkTheme(a){const b=this._dom.find(".lh-vars",this._document);"undefined"===typeof a?b.classList.toggle("dark"):b.classList.toggle("dark",a)}_updateStickyHeaderOnScroll(){var a=this.topbarEl.getBoundingClientRect().bottom,b=this.scoreScaleEl.getBoundingClientRect().top;a=a>=b;b=Array.from(this._document.querySelectorAll(".lh-category"));b=b.filter(d=>
0>d.getBoundingClientRect().top-window.innerHeight/2);var c=0<b.length?b.length-1:0;b=this.stickyHeaderEl.querySelectorAll(".lh-gauge__wrapper");c=b[c];b=b[0].getBoundingClientRect().left;b=c.getBoundingClientRect().left-b;this.highlightEl.style.transform=`translate(${b}px)`;this.stickyHeaderEl.classList.toggle("lh-sticky-header--visible",a)}}
class DropDown{constructor(a){this._dom=a;this.onDocumentKeyDown=this.onDocumentKeyDown.bind(this);this.onMenuFocusOut=this.onMenuFocusOut.bind(this);this._getNextMenuItem=this._getNextMenuItem.bind(this);this._getNextSelectableNode=this._getNextSelectableNode.bind(this);this._getPreviousMenuItem=this._getPreviousMenuItem.bind(this)}close(){this._toggleEl.classList.remove("active");this._toggleEl.setAttribute("aria-expanded","false");this._menuEl.contains(this._dom.document().activeElement)&&this._toggleEl.focus();
this._menuEl.removeEventListener("focusout",this.onMenuFocusOut);this._dom.document().removeEventListener("keydown",this.onDocumentKeyDown)}open(a){this._toggleEl.classList.contains("active")?a.focus():this._menuEl.addEventListener("transitionend",()=>{a.focus()},{once:!0});this._toggleEl.classList.add("active");this._toggleEl.setAttribute("aria-expanded","true");this._menuEl.addEventListener("focusout",this.onMenuFocusOut);this._dom.document().addEventListener("keydown",this.onDocumentKeyDown)}onDocumentKeyDown(a){27===
a.keyCode&&this.close()}onMenuFocusOut(a){a=a.relatedTarget;this._menuEl.contains(a)||this.close()}_getNextSelectableNode(a,b){a=a.filter(c=>c instanceof HTMLElement&&!c.hasAttribute("disabled")&&"none"!==window.getComputedStyle(c).display?!0:!1);b=b?a.indexOf(b)+1:0;b>=a.length&&(b=0);return a[b]}_getNextMenuItem(a){const b=Array.from(this._menuEl.childNodes);return this._getNextSelectableNode(b,a)}_getPreviousMenuItem(a){const b=Array.from(this._menuEl.childNodes).reverse();return this._getNextSelectableNode(b,
a)}}"undefined"!==typeof module&&module.exports?module.exports=ReportUIFeatures:self.ReportUIFeatures=ReportUIFeatures;/*
 Copyright 2019 The Lighthouse Authors. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/
const LineVisibility={ALWAYS:0,WHEN_COLLAPSED:1,WHEN_EXPANDED:2},LineContentType={CONTENT_NORMAL:0,CONTENT_HIGHLIGHTED:1,PLACEHOLDER:2,MESSAGE:3},classNamesByContentType={[LineContentType.CONTENT_NORMAL]:["lh-snippet__line--content"],[LineContentType.CONTENT_HIGHLIGHTED]:["lh-snippet__line--content","lh-snippet__line--content-highlighted"],[LineContentType.PLACEHOLDER]:["lh-snippet__line--placeholder"],[LineContentType.MESSAGE]:["lh-snippet__line--message"]};
function getLineAndPreviousLine(a,b){return{line:a.find(c=>c.lineNumber===b),previousLine:a.find(c=>c.lineNumber===b-1)}}function getMessagesForLineNumber(a,b){return a.filter(c=>c.lineNumber===b)}
class SnippetRenderer{static renderHeader(a,b,c,d,e){var f=Util.filterRelevantLines(c.lines,c.lineMessages,2);f=f.length<c.lines.length;b=a.cloneTemplate("#tmpl-lh-snippet__header",b);a.find(".lh-snippet__title",b).textContent=c.title;const {snippetCollapseButtonLabel:g,snippetExpandButtonLabel:h}=Util.i18n.strings;a.find(".lh-snippet__btn-label-collapse",b).textContent=g;a.find(".lh-snippet__btn-label-expand",b).textContent=h;const k=a.find(".lh-snippet__toggle-expand",b);f?k.addEventListener("click",
()=>e()):k.remove();c.node&&a.isDevTools()&&(a=a.find(".lh-snippet__node",b),a.appendChild(d.renderNode(c.node)));return b}static renderSnippetLine(a,b,{content:c,lineNumber:d,truncated:e,contentType:f,visibility:g}){b=a.cloneTemplate("#tmpl-lh-snippet__line",b);b=a.find(".lh-snippet__line",b);const {classList:h}=b;classNamesByContentType[f].forEach(k=>h.add(k));g===LineVisibility.WHEN_COLLAPSED?h.add("lh-snippet__show-if-collapsed"):g===LineVisibility.WHEN_EXPANDED&&h.add("lh-snippet__show-if-expanded");
c+=e?"\u2026":"";e=a.find(".lh-snippet__line code",b);f===LineContentType.MESSAGE?e.appendChild(a.convertMarkdownLinkSnippets(c)):e.textContent=c;a.find(".lh-snippet__line-number",b).textContent=d.toString();return b}static renderMessage(a,b,c){return SnippetRenderer.renderSnippetLine(a,b,{lineNumber:" ",content:c.message,contentType:LineContentType.MESSAGE})}static renderOmittedLinesPlaceholder(a,b,c){return SnippetRenderer.renderSnippetLine(a,b,{lineNumber:"\u2026",content:"",visibility:c,contentType:LineContentType.PLACEHOLDER})}static renderSnippetContent(a,
b,c){const d=a.cloneTemplate("#tmpl-lh-snippet__content",b),e=a.find(".lh-snippet__snippet-inner",d);c.generalMessages.forEach(f=>e.append(SnippetRenderer.renderMessage(a,b,f)));e.append(SnippetRenderer.renderSnippetLines(a,b,c));return d}static renderSnippetLines(a,b,c){const {lineMessages:d,generalMessages:e,lineCount:f,lines:g}=c;c=Util.filterRelevantLines(c.lines,c.lineMessages,2);const h=0<e.length&&0===d.length,k=a.createFragment();var p=!1;for(let m=1;m<=f;m++){const {line:q,previousLine:u}=
getLineAndPreviousLine(g,m),{line:t,previousLine:v}=getLineAndPreviousLine(c,m);var n=!!t,l=!!v;l&&!n&&(p=!0);n&&p&&(k.append(SnippetRenderer.renderOmittedLinesPlaceholder(a,b,LineVisibility.WHEN_COLLAPSED)),p=!1);n=!q&&!!u;l=!q&&1===m;if(n||l)p=(p=!c.some(r=>r.lineNumber>m))||1===m,k.append(SnippetRenderer.renderOmittedLinesPlaceholder(a,b,p?LineVisibility.WHEN_EXPANDED:LineVisibility.ALWAYS)),p=!1;q&&(n=getMessagesForLineNumber(d,m),l=0<n.length||h,l=Object.assign({},q,{contentType:l?LineContentType.CONTENT_HIGHLIGHTED:
LineContentType.CONTENT_NORMAL,visibility:t?LineVisibility.ALWAYS:LineVisibility.WHEN_EXPANDED}),k.append(SnippetRenderer.renderSnippetLine(a,b,l)),n.forEach(r=>{k.append(SnippetRenderer.renderMessage(a,b,r))}))}return k}static render(a,b,c,d){b=a.cloneTemplate("#tmpl-lh-snippet",b);const e=a.find(".lh-snippet",b);d=SnippetRenderer.renderHeader(a,b,c,d,()=>e.classList.toggle("lh-snippet--expanded"));a=SnippetRenderer.renderSnippetContent(a,b,c);e.append(d,a);return e}}
"undefined"!==typeof module&&module.exports?module.exports=SnippetRenderer:self.SnippetRenderer=SnippetRenderer;/*
 Copyright 2021 The Lighthouse Authors. All Rights Reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/
const btoa_="undefined"!==typeof btoa?btoa:a=>Buffer.from(a).toString("base64"),atob_="undefined"!==typeof atob?atob:a=>Buffer.from(a,"base64").toString();
async function toBase64(a,b){var c=(new TextEncoder).encode(a);b.gzip&&("undefined"!==typeof CompressionStream?(a=new CompressionStream("gzip"),b=a.writable.getWriter(),b.write(c),b.close(),c=await (new Response(a.readable)).arrayBuffer(),c=new Uint8Array(c)):(c=window.pako,c=c.gzip(a)));a="";for(b=0;b<c.length;b+=5E3)a+=String.fromCharCode(...c.subarray(b,b+5E3));return btoa_(a)}
function fromBase64(a,b){a=atob_(a);a=Uint8Array.from(a,c=>c.charCodeAt(0));return b.gzip?(b=window.pako,b.ungzip(a,{to:"string"})):(new TextDecoder).decode(a)}"undefined"!==typeof module&&module.exports?module.exports={toBase64,fromBase64}:self.TextEncoding={toBase64,fromBase64};const RATINGS={PASS:{label:"pass",minScore:.9},AVERAGE:{label:"average",minScore:.5},FAIL:{label:"fail"},ERROR:{label:"error"}},listOfTlds="com co gov edu ac org go gob or net in ne nic gouv web spb blog jus kiev mil wi qc ca bel on".split(" ");
class Util{static prepareReportResult(a){const b=JSON.parse(JSON.stringify(a));b.configSettings.locale||(b.configSettings.locale="en");b.configSettings.formFactor||(b.configSettings.formFactor=b.configSettings.emulatedFormFactor);for(const d of Object.values(b.audits)){if("not_applicable"===d.scoreDisplayMode||"not-applicable"===d.scoreDisplayMode)d.scoreDisplayMode="notApplicable";if(d.details){if(void 0===d.details.type||"diagnostic"===d.details.type)d.details.type="debugdata";if("filmstrip"===
d.details.type)for(const e of d.details.items)e.data.startsWith("data:image/jpeg;base64,")||(e.data="data:image/jpeg;base64,"+e.data)}}if("object"!==typeof b.categories)throw Error("No categories provided.");const c=new Map;for(const d of Object.values(b.categories))d.auditRefs.forEach(e=>{e.relevantAudits&&e.relevantAudits.forEach(f=>{const g=c.get(f)||[];g.push(e);c.set(f,g)})}),d.auditRefs.forEach(e=>{const f=b.audits[e.id];e.result=f;c.has(e.id)&&(e.relevantMetrics=c.get(e.id));b.stackPacks&&
b.stackPacks.forEach(g=>{g.descriptions[e.id]&&(e.stackPacks=e.stackPacks||[],e.stackPacks.push({title:g.title,iconDataURL:g.iconDataURL,description:g.descriptions[e.id]}))})});return b}static showAsPassed(a){switch(a.scoreDisplayMode){case "manual":case "notApplicable":return!0;case "error":case "informative":return!1;default:return Number(a.score)>=RATINGS.PASS.minScore}}static calculateRating(a,b){if("manual"===b||"notApplicable"===b)return RATINGS.PASS.label;if("error"===b)return RATINGS.ERROR.label;
if(null===a)return RATINGS.FAIL.label;b=RATINGS.FAIL.label;a>=RATINGS.PASS.minScore?b=RATINGS.PASS.label:a>=RATINGS.AVERAGE.minScore&&(b=RATINGS.AVERAGE.label);return b}static splitMarkdownCodeSpans(a){const b=[];a=a.split(/`(.*?)`/g);for(let c=0;c<a.length;c++){const d=a[c];if(!d)continue;const e=0!==c%2;b.push({isCode:e,text:d})}return b}static splitMarkdownLink(a){const b=[];for(a=a.split(/\[([^\]]+?)\]\((https?:\/\/.*?)\)/g);a.length;){const [c,d,e]=a.splice(0,3);c&&b.push({isLink:!1,text:c});
d&&e&&b.push({isLink:!0,text:d,linkHref:e})}return b}static getURLDisplayName(a,b){b=b||{numPathParts:void 0,preserveQuery:void 0,preserveHost:void 0};const c=void 0!==b.numPathParts?b.numPathParts:2,d=void 0!==b.preserveQuery?b.preserveQuery:!0,e=b.preserveHost||!1;if("about:"===a.protocol||"data:"===a.protocol)b=a.href;else{b=a.pathname;const f=b.split("/").filter(g=>g.length);c&&f.length>c&&(b="\u2026"+f.slice(-1*c).join("/"));e&&(b=`${a.host}/${b.replace(/^\//,"")}`);d&&(b=`${b}${a.search}`)}b=
b.replace(/([a-f0-9]{7})[a-f0-9]{13}[a-f0-9]*/g,"$1\u2026");b=b.replace(/([a-zA-Z0-9-_]{9})(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9-_]{10,}/g,"$1\u2026");b=b.replace(/(\d{3})\d{6,}/g,"$1\u2026");b=b.replace(/\u2026+/g,"\u2026");64<b.length&&b.includes("?")&&(b=b.replace(/\?([^=]*)(=)?.*/,"?$1$2\u2026"),64<b.length&&(b=b.replace(/\?.*/,"?\u2026")));64<b.length&&(a=b.lastIndexOf("."),b=0<=a?b.slice(0,63-(b.length-a))+`${"\u2026"}${b.slice(a)}`:b.slice(0,63)+"\u2026");return b}static parseURL(a){a=
new URL(a);return{file:Util.getURLDisplayName(a),hostname:a.hostname,origin:a.origin}}static createOrReturnURL(a){return a instanceof URL?a:new URL(a)}static getTld(a){a=a.split(".").slice(-2);return listOfTlds.includes(a[0])?`.${a.join(".")}`:`.${a[a.length-1]}`}static getRootDomain(a){a=Util.createOrReturnURL(a).hostname;var b=Util.getTld(a);b=b.split(".");return a.split(".").slice(-b.length).join(".")}static getEnvironmentDisplayValues(a){a=Util.getEmulationDescriptions(a);return[{name:Util.i18n.strings.runtimeSettingsDevice,
description:a.deviceEmulation},{name:Util.i18n.strings.runtimeSettingsNetworkThrottling,description:a.networkThrottling},{name:Util.i18n.strings.runtimeSettingsCPUThrottling,description:a.cpuThrottling}]}static getEmulationDescriptions(a){let b;var c=a.throttling;switch(a.throttlingMethod){case "provided":c=b=Util.i18n.strings.throttlingProvided;break;case "devtools":const {cpuSlowdownMultiplier:d,requestLatencyMs:e}=c;b=`${Util.i18n.formatNumber(d)}x slowdown (DevTools)`;c=`${Util.i18n.formatNumber(e)}${"\u00a0"}ms HTTP RTT, `+
`${Util.i18n.formatNumber(c.downloadThroughputKbps)}${"\u00a0"}Kbps down, `+`${Util.i18n.formatNumber(c.uploadThroughputKbps)}${"\u00a0"}Kbps up (DevTools)`;break;case "simulate":const {cpuSlowdownMultiplier:f,rttMs:g,throughputKbps:h}=c;b=`${Util.i18n.formatNumber(f)}x slowdown (Simulated)`;c=`${Util.i18n.formatNumber(g)}${"\u00a0"}ms TCP RTT, `+`${Util.i18n.formatNumber(h)}${"\u00a0"}Kbps throughput (Simulated)`;break;default:c=b=Util.i18n.strings.runtimeUnknown}a={mobile:Util.i18n.strings.runtimeMobileEmulation,
desktop:Util.i18n.strings.runtimeDesktopEmulation}[a.formFactor]||Util.i18n.strings.runtimeNoEmulation;return{deviceEmulation:a,cpuThrottling:b,networkThrottling:c}}static filterRelevantLines(a,b,c){if(0===b.length)return a.slice(0,2*c+1);const d=new Set;b=b.sort((e,f)=>(e.lineNumber||0)-(f.lineNumber||0));b.forEach(({lineNumber:e})=>{var f=e-c;for(e+=c;1>f;)f++,e++;for(d.has(f-3-1)&&(f-=3);f<=e;f++){const g=f;d.add(g)}});return a.filter(e=>d.has(e.lineNumber))}static isPluginCategory(a){return a.startsWith("lighthouse-plugin-")}}
Util.reportJson=null;Util.getUniqueSuffix=(()=>{let a=0;return function(){return a++}})();Util.i18n=null;
Util.UIStrings={varianceDisclaimer:"Values are estimated and may vary. The [performance score is calculated](https://web.dev/performance-scoring/) directly from these metrics.",calculatorLink:"See calculator.",showRelevantAudits:"Show audits relevant to:",opportunityResourceColumnLabel:"Opportunity",opportunitySavingsColumnLabel:"Estimated Savings",errorMissingAuditInfo:"Report error: no audit information",errorLabel:"Error!",warningHeader:"Warnings: ",warningAuditsGroupTitle:"Passed audits but with warnings",
passedAuditsGroupTitle:"Passed audits",notApplicableAuditsGroupTitle:"Not applicable",manualAuditsGroupTitle:"Additional items to manually check",toplevelWarningsMessage:"There were issues affecting this run of Lighthouse:",crcInitialNavigation:"Initial Navigation",crcLongestDurationLabel:"Maximum critical path latency:",snippetExpandButtonLabel:"Expand snippet",snippetCollapseButtonLabel:"Collapse snippet",lsPerformanceCategoryDescription:"[Lighthouse](https://developers.google.com/web/tools/lighthouse/) analysis of the current page on an emulated mobile network. Values are estimated and may vary.",
labDataTitle:"Lab Data",thirdPartyResourcesLabel:"Show 3rd-party resources",viewTreemapLabel:"View Treemap",dropdownPrintSummary:"Print Summary",dropdownPrintExpanded:"Print Expanded",dropdownCopyJSON:"Copy JSON",dropdownSaveHTML:"Save as HTML",dropdownSaveJSON:"Save as JSON",dropdownViewer:"Open in Viewer",dropdownSaveGist:"Save as Gist",dropdownDarkTheme:"Toggle Dark Theme",runtimeSettingsTitle:"Runtime Settings",runtimeSettingsUrl:"URL",runtimeSettingsFetchTime:"Fetch Time",runtimeSettingsDevice:"Device",
runtimeSettingsNetworkThrottling:"Network throttling",runtimeSettingsCPUThrottling:"CPU throttling",runtimeSettingsChannel:"Channel",runtimeSettingsUA:"User agent (host)",runtimeSettingsUANetwork:"User agent (network)",runtimeSettingsBenchmark:"CPU/Memory Power",runtimeSettingsAxeVersion:"Axe version",footerIssue:"File an issue",runtimeNoEmulation:"No emulation",runtimeMobileEmulation:"Emulated Moto G4",runtimeDesktopEmulation:"Emulated Desktop",runtimeUnknown:"Unknown",throttlingProvided:"Provided by environment"};
"undefined"!==typeof module&&module.exports?module.exports=Util:self.Util=Util;
